apiVersion: v1
kind: Secret
metadata:
  name: sophistry-secrets
  namespace: sophistry
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-me"
  POSTGRES_DB: "sophistry"
  POSTGRES_USER: "sophistry"
  POSTGRES_PASSWORD: "change-me-strong"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_CACHE_URL: "redis://redis:6379/1"
