apiVersion: v1
kind: Secret
metadata:
  name: sophistry-secrets
  namespace: sophistry
type: Opaque
stringData:
  DJANGO_SECRET_KEY: ""
  POSTGRES_DB: "sophistry"
  POSTGRES_USER: "sophistry"
  POSTGRES_PASSWORD: ""
  REDIS_URL: "redis://redis:6379/0"
  REDIS_CACHE_URL: "redis://redis:6379/1"
