apiVersion: v1
kind: Secret
metadata:
  name: sophistry-secrets
  namespace: sophistry
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "de1f67aa424f8cdb3c642823168cdf74"
  POSTGRES_DB: "sophistry"
  POSTGRES_USER: "sophistry"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_CACHE_URL: "redis://redis:6379/1"
