apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophistry-web
  namespace: sophistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophistry-web
  template:
    metadata:
      labels:
        app: sophistry-web
    spec:
      containers:
        - name: web
          image: briankmatheson/sophistry-web:0.7.1
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: sophistry-config
            - secretRef:
                name: sophistry-secrets
          env:
            - name: ROLE
              value: web
            - name: BACKEND_BASE_URL
              value: https://app.sophistry.online/api
---
apiVersion: v1
kind: Service
metadata:
  name: sophistry-web
  namespace: sophistry
spec:
  selector:
    app: sophistry-web
  ports:
    - port: 80
      targetPort: 80
