apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophistry-web
  namespace: sophistry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sophistry-web
  template:
    metadata:
      labels:
        app: sophistry-web
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: web
          image: briankmatheson/sophistry-web:0.3.0
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: sophistry-config
            - secretRef:
                name: sophistry-secrets
          env:
            - name: ROLE
              value: web
---
apiVersion: v1
kind: Service
metadata:
  name: sophistry-web
  namespace: sophistry
spec:
  selector:
    app: sophistry-web
  ports:
    - port: 80
      targetPort: 8000
