apiVersion: batch/v1
kind: Job
metadata:
  name: sophistry-migrate
  namespace: sophistry
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          imagePullPolicy: Always
          image: briankmatheson/sophistry-worker:0.9.8
          envFrom:
            - configMapRef:
                name: sophistry-config
            - secretRef:
                name: sophistry-secrets
          env:
            - name: ROLE
              value: migrate
