apiVersion: apps/v1
kind: Deployment
metadata:
  name: sophistry-com
  namespace: sophistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sophistry-com
  template:
    metadata:
      labels:
        app: sophistry-com
    spec:
      containers:
        - name: web
          image: briankmatheson/sophistry-com:0.8.7
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sophistry-com
  namespace: sophistry
spec:
  selector:
    app: sophistry-com
  ports:
    - port: 80
      targetPort: 80
